POST http://localhost:4002/products
content-type: application/json

{
    "name": "Cachaça",
    "price": 12
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/acad3488-3b69-41c2-963b-512d38e3ce8e

###

GET http://localhost:4002/products/471f3a7d-464c-47fd-b2f1-b7e1a5dd34bf