POST http://localhost:4002/products
content-type: application/json

{
    "name": "Borracha",
    "price": 2.00
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/12ec951b-6238-439d-a22a-81b745120fd0

###

PUT http://localhost:4002/products/12ec951b-6238-439d-a22a-81b745120fd0
content-type: application/json

{
    "name": "Borracha",
    "price": 0.5
}

###
DELETE http://localhost:4002/products/12ec951b-6238-439d-a22a-81b745120fd0